# Generated by Django 5.1.1 on 2024-09-21 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('biography', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('max_borrow_limit', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('return_date', models.DateField()),
                ('num_of_books_borrowed', models.PositiveSmallIntegerField()),
                ('limit_reached', models.BooleanField(default=False)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='LibraryManagementSystem.library')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=10)),
                ('publication_date', models.DateField()),
                ('genre', models.CharField(choices=[('A', 'A'), ('AA', 'AA'), ('C', 'C'), ('CR', 'CR'), ('D', 'D'), ('F', 'F'), ('HIS', 'HIS'), ('H', 'H'), ('M', 'M'), ('R', 'R'), ('SF', 'SF'), ('T', 'T'), ('W', 'W')], default='A', max_length=3)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_book_avaiable', models.BooleanField(default=True)),
                ('author', models.ManyToManyField(related_name='books', to='LibraryManagementSystem.author')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='LibraryManagementSystem.library')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('membership_date', models.DateTimeField(auto_now_add=True)),
                ('borrow_records', models.ManyToManyField(blank=True, related_name='members', to='LibraryManagementSystem.borrowrecord')),
                ('library', models.ManyToManyField(related_name='members', to='LibraryManagementSystem.library')),
            ],
        ),
    ]
