# Generated by Django 5.1.1 on 2024-09-21 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name': 'Library', 'verbose_name_plural': 'Libraries'},
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('A', 'Action'), ('AA', 'Adventure'), ('C', 'Comedy'), ('CR', 'Crime'), ('D', 'Drama'), ('F', 'Fantasy'), ('HIS', 'Historical'), ('H', 'Horror'), ('M', 'Mystery'), ('R', 'Romance'), ('SF', 'Science Fiction'), ('T', 'Thriller'), ('W', 'Western')], default='A', max_length=3),
        ),
        migrations.CreateModel(
            name='BorrowBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('return_date', models.DateField()),
                ('num_of_books_borrowed', models.PositiveSmallIntegerField()),
                ('limit_reached', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_records', to='LibraryManagementSystem.book')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='LibraryManagementSystem.library')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_records', to='LibraryManagementSystem.member')),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='borrow_records',
            field=models.ManyToManyField(blank=True, related_name='members', to='LibraryManagementSystem.borrowbook'),
        ),
        migrations.DeleteModel(
            name='BorrowRecord',
        ),
    ]
