# Generated by Django 5.1.1 on 2024-09-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0003_alter_book_isbn_alter_book_library'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_book_avaiable',
            new_name='is_book_available',
        ),
    ]
