# Generated by Django 5.1.1 on 2024-09-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0004_rename_is_book_avaiable_book_is_book_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowbook',
            options={'verbose_name': 'Loan Book', 'verbose_name_plural': 'Loan Books'},
        ),
        migrations.RemoveField(
            model_name='borrowbook',
            name='limit_reached',
        ),
        migrations.RemoveField(
            model_name='borrowbook',
            name='num_of_books_borrowed',
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='status',
            field=models.CharField(choices=[('B', 'Borrowed'), ('R', 'Reserved'), ('RR', 'Returned')], default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='limit_reached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='num_of_books_borrowed',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
