# Generated by Django 5.1.1 on 2024-09-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0005_alter_borrowbook_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
