# Generated by Django 5.1.1 on 2024-09-21 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0006_alter_borrowbook_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='borrow_records',
        ),
        migrations.RemoveField(
            model_name='member',
            name='num_of_books_borrowed',
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_records', to='LibraryManagementSystem.library'),
        ),
    ]
