# Generated by Django 5.1.1 on 2024-09-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0007_remove_member_borrow_records_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='limit_reached',
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='limit_reached',
            field=models.BooleanField(default=False),
        ),
    ]
