# Generated by Django 5.1.1 on 2024-09-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0008_remove_member_limit_reached_borrowbook_limit_reached'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
