# Generated by Django 5.1.1 on 2024-09-23 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0009_book_available_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='LibraryHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
                ('opening_times', models.TimeField()),
                ('closing_times', models.TimeField()),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='LibraryManagementSystem.library')),
            ],
            options={
                'unique_together': {('library', 'day_of_week')},
            },
        ),
    ]
