# Generated by Django 5.1.1 on 2024-09-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0010_library_location_libraryhours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libraryhours',
            old_name='closing_times',
            new_name='closing_time',
        ),
        migrations.RenameField(
            model_name='libraryhours',
            old_name='opening_times',
            new_name='opening_time',
        ),
    ]
