# Generated by Django 5.1.1 on 2024-10-12 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagementSystem', '0012_book_is_reserved_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='status',
            field=models.CharField(choices=[('B', 'Borrowed'), ('RR', 'Returned')], max_length=2),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='LibraryManagementSystem.member'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('y', 'Cancelled')], max_length=1),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='LibraryManagementSystem.member')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveBigIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_queue', to='LibraryManagementSystem.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_queue', to='LibraryManagementSystem.member')),
            ],
        ),
    ]
