# Generated by Django 5.1.1 on 2024-09-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_remove_session_end_time_remove_session_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
