# Generated by Django 5.1.1 on 2024-09-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_alter_event_title_alter_session_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_capacity',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
