# Generated by Django 5.1.1 on 2024-09-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0004_event_max_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_capacity',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
